In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [2]:
df = pd.read_csv('/Users/emilyjohnson/Downloads/bottles.csv')

In [3]:
df

     Unnamed: 0  Depthm  T_degC   Salnty  O2ml_L    STheta
0        282769       0  16.810  33.6600   5.430  24.53100
1        657442      91  13.700  33.3240   5.740  24.95700
2        157944       9  12.400  33.5900   6.350  25.41900
3         45210     125   9.240  32.8850   5.290  25.42700
4        474774      30  16.330  35.1900     NaN  25.82000
..          ...     ...     ...      ...     ...       ...
995      234834     381   7.840  34.4200     NaN  26.84800
996      503295      41  13.760  33.4160   6.340  25.01500
997      165309     250   9.590  34.4840     NaN  26.62300
998      544600     250   8.770  34.1990     NaN  26.53200
999      874919     250   7.593  33.9939   2.351  26.55027

[1000 rows x 6 columns]

In [4]:
print(df.isnull().sum())

Unnamed: 0      0
Depthm          0
T_degC         13
Salnty         58
O2ml_L        201
STheta         66
dtype: int64

In [8]:
df = df.dropna(subset=['T_degC'])

In [9]:
df = df.drop(columns=['Unnamed: 0'])

In [10]:
df

     Depthm  T_degC   Salnty  O2ml_L    STheta
0         0  16.810  33.6600   5.430  24.53100
1        91  13.700  33.3240   5.740  24.95700
2         9  12.400  33.5900   6.350  25.41900
3       125   9.240  32.8850   5.290  25.42700
4        30  16.330  35.1900     NaN  25.82000
..      ...     ...      ...     ...       ...
995     381   7.840  34.4200     NaN  26.84800
996      41  13.760  33.4160   6.340  25.01500
997     250   9.590  34.4840     NaN  26.62300
998     250   8.770  34.1990     NaN  26.53200
999     250   7.593  33.9939   2.351  26.55027

[987 rows x 5 columns]

In [11]:
df = df.rename(columns={'Depthm' : 'Depth_meters', 'T_degC' : 'Temp_C', 'Salnty' : 'Salinity', 'O2ml_l' : 'Oxygen', 'STheta' : 'Density'})

In [12]:
df

     Depth_meters  Temp_C  Salinity  O2ml_L   Density
0               0  16.810   33.6600   5.430  24.53100
1              91  13.700   33.3240   5.740  24.95700
2               9  12.400   33.5900   6.350  25.41900
3             125   9.240   32.8850   5.290  25.42700
4              30  16.330   35.1900     NaN  25.82000
..            ...     ...       ...     ...       ...
995           381   7.840   34.4200     NaN  26.84800
996            41  13.760   33.4160   6.340  25.01500
997           250   9.590   34.4840     NaN  26.62300
998           250   8.770   34.1990     NaN  26.53200
999           250   7.593   33.9939   2.351  26.55027

[987 rows x 5 columns]

In [13]:
df = df.rename(columns={'O2ml_L' : 'Oxygen'})

In [14]:
df

     Depth_meters  Temp_C  Salinity  Oxygen   Density
0               0  16.810   33.6600   5.430  24.53100
1              91  13.700   33.3240   5.740  24.95700
2               9  12.400   33.5900   6.350  25.41900
3             125   9.240   32.8850   5.290  25.42700
4              30  16.330   35.1900     NaN  25.82000
..            ...     ...       ...     ...       ...
995           381   7.840   34.4200     NaN  26.84800
996            41  13.760   33.4160   6.340  25.01500
997           250   9.590   34.4840     NaN  26.62300
998           250   8.770   34.1990     NaN  26.53200
999           250   7.593   33.9939   2.351  26.55027

[987 rows x 5 columns]

In [15]:
df['Salinity'] = df['Salinity'].fillna(df['Salinity'].mean())
df['Oxygen'] = df['Oxygen'].fillna(df['Oxygen'].mean())
df['Density'] = df['Density'].fillna(df['Density'].mean())

In [16]:
print(df.isnull().sum())

Depth_meters    0
Temp_C          0
Salinity        0
Oxygen          0
Density         0
dtype: int64